<?php

$request = 'SELECT name, products.description, products.price FROM `products_categories` JOIN products ON products_categories.product_id = products.id JOIN categories ON products_categories.category_id = categories.id WHERE title = "' . $param .'"';


$query = $db->prepare("$request");
$query->execute();
$products = $query->fetchAll();

?>
    <a href="index.php">Retour à l'accueil</a>
   <h2><?=$param?></h2>
   <?php

   foreach($products as $product){

?> 
<article class="product-article">

    <h3><?=$product[0]?></h3>
    <p><?=$product[1]?></p>
    <p class='price'><?=$product[2]?> €</p>
</article>
<?php
   }
   
   ?>
