<?php


?>




<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>3WA Trade</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <h1>3WA Trade</h1>
   <nav class="categories-nav">

       <?php
    foreach( $categories as $category){
        ?> <a href="index.php?cat=<?=$category[0]?>"> <div class="category-box">
            <h2 class="category-title"><?=$category[0]?><h2>
                </div> </a>
                <?php
    }
    
    ?>
</nav>
</body>
</html>