<h2>Welcome to the fabulous 3WA Trade</h2>
<p>Only real items for sale</p>
<form action="index.php" method="GET">
    <fieldset>
        <legend>Choisissez votre thème:</legend>
        <label for="color">Couleur de fond:</label>
        <input type="color" name="color" id="color">
        <button type="submit">Appliquer</button>
        <a href="index.php?cookie=no">SUPPRIMMER le cookie</a>
    </fieldset>
</form>