<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>3WA Trade</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body style="background-color:<?=$color?>">
   <header>

   <h1>3WA Trade</h1>
   <nav class="categories-nav">

       <?php
    foreach( $categories as $category){
        ?> <a href="index.php?cat=<?=$category[0]?>"> <div class="category-box">
            <p class="category-title"><?=$category[0]?><p>
                </div> </a>
                <?php
    }
    
    ?>
</nav>
   </header>
   <main>
    <?php include $template ?>
   </main>
</body>
</html>