
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Authentification</title>
</head>
<body>
    <h1>Connexion</h1>
    <form action="secret.php" method="post">
        <label for="login">Identifiant :</label>
        <input type="text" name="login" id="login" >
        <label for="password">Mot de passe :</label>
        <input type="password" name="password" id="password" >
        <button type="submit">Se connecter</button>
    </form>
</body>
</html>